parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

parser: babel-eslint

plugins:
  - react

rules:
  block-scoped-var:
    - 2
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-unused-vars:
    - 2
    - args: all
      argsIgnorePattern: ^_

  # Stylistic
  array-bracket-spacing:
    - 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  camelcase: 0
  comma-dangle:
    - 0
  comma-spacing:
    - 2
  computed-property-spacing:
    - 2
    - never
  indent:
    - 1
    - 2
    - SwitchCase: 0
  keyword-spacing:
    - 2
  linebreak-style:
    - 2
    - unix
  object-curly-spacing:
    - 2
    - never
  quotes:
    - 1
    - single
  semi:
    - 1
    - always
  semi-spacing:
    - 2
  space-in-parens:
    - 2
    - never
  space-before-function-paren:
    - 1
    - anonymous: always
      named: never

  # ES6
  no-var:
    - 2

  # React
  react/display-name: 0
  react/prop-types: 0

env:
  es6: true
  browser: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
